### ISSUE TITLE
MongoDB::Wire can't inherit from BSON

### ISSUE THREAD

**Issue by paultcochrane** [MARTIMM/mongo-perl6-driver#6]
Running the tests via `prove -lr --exec="perl6 -Ilib" t` gives many test failures with the following error message:

    ===SORRY!=== Error while compiling /home/cochrane/Projekte/OSSProjekte/mongo-perl6-driver/lib/MongoDB/Wire.pm
    BSON does not support inheritance, so MongoDB::Wire cannot inherit from it
    at /home/cochrane/Projekte/OSSProjekte/mongo-perl6-driver/lib/MongoDB/Wire.pm:9

I see that the latest commit to the repo is two days ago, so I'm guessing I'm doing something wrong here by running the tests like this.  Nevertheless, I thought it a good idea to let you know about the issue.  `BSON` was installed via `panda install BSON`.

My `perl6` version is:

    $ perl6 --version
    This is perl6 version 2015.09-383-gf0d4820 built on MoarVM version 2015.09-85-g3a00a08

Cheers,

Paul

**Comment by MARTIMM** [comment]
Hi Paul,

Thanks for your message. I've been very busy with all sorts of things and completely missed your message. I am very sorry. It happens because a lot of mail is coming in from perl6 mail lists, mongodb, neo4j (for a driver to made later) etc. So the issues are snowed under a thick layer of other messages.

In the mean time a lot is changed for perl6, the BSON package as well as the mongo driver package so to find this particular error you mentioned above is perhaps impossible to do.

At this very moment I had uploaded the packages to git and on Travis BSON tested fine but when BSON was loaded as a dependency I got errors like ```Numeric overflow```(Retested a moment ago and now it fails with the same numeric overflow errors in the double precision tests). The mongo driver fails with strange errors like ```Dynamic variable @*INC not found ``` and ```Could not find BSON:ver<True>:auth<True>:api<True> ```.

Travis has been ordered (by me) to pick the newest perl6 version and I've seen that it is a few hundred steps ahead of my local installation (from last week, mind you, man do they go fast!). So that might be the reason for new failing things. Here just run a local ```panda install MongoDB``` and it went fine. ```version 2015.11-143-g7046681 built on MoarVM version 2015.11-19-g623eadf implementing Perl v6.b.```. Travis runned with ```version 2015.11-337-gc8bd575 built on MoarVM version 2015.11-31-g0670e3d implementing Perl v6.b.```.

So, not very hopeful. But soon its Christmas and the perl 6 will stabilize a bit.
Thanks again for your message although I couldn't help you. 
Marcel

**Comment by MARTIMM** [comment]
The problems were found quicker than I thought. See issue double trouble. I will close this one for now.

**Comment by paultcochrane** [comment]
Hi Marcel,

don't worry about the late reply, I can fully understand how other things
take up more time and one can miss emails and messages in the daily flood of
information :-)

I need to check the issue with a current Rakudo, however, the problem has
most probably already been fixed in the meantime.  Many thanks for answering
the ticket!

Cheers,

Paul

**Comment by MARTIMM** [comment]
Hi Paul,
Mongodb is at this moment in a big rewrite because of a change in the use 
of hashes as the storage vehicle into a newly written document class. 
Although it is tested (in BSON) changes are needed to get better performance.
Regards,
Marcel
